development:
  adapter: postgresql
  encoding: unicode
  database: pairwithme_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: pairwithme_test
  pool: 5
  username:
  password:
